<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-22T16:31:28 IST" name="Suite" finished-at="2023-11-22T16:32:06 IST" duration-ms="37317">
    <groups>
    </groups>
    <test started-at="2023-11-22T16:31:28 IST" name="chrometest" finished-at="2023-11-22T16:32:06 IST" duration-ms="37317">
      <class name="testCases.TC_001_SFI_All_Mobile">
        <test-method is-config="true" signature="onStart(org.testng.ITestContext)[pri:0, instance:testCases.TC_001_SFI_All_Mobile@53d102a2]" started-at="2023-11-22T16:31:28 IST" name="onStart" finished-at="2023-11-22T16:31:28 IST" duration-ms="446" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@28ee0a3c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onStart -->
        <test-method is-config="true" signature="testName()[pri:0, instance:testCases.TC_001_SFI_All_Mobile@53d102a2]" started-at="2023-11-22T16:31:28 IST" name="testName" finished-at="2023-11-22T16:31:28 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testName -->
        <test-method is-config="true" signature="configureAppium()[pri:0, instance:testCases.TC_001_SFI_All_Mobile@53d102a2]" started-at="2023-11-22T16:31:28 IST" name="configureAppium" finished-at="2023-11-22T16:31:46 IST" duration-ms="17481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureAppium -->
        <test-method signature="TestMobileIndividualControls()[pri:0, instance:testCases.TC_001_SFI_All_Mobile@53d102a2]" started-at="2023-11-22T16:31:46 IST" name="TestMobileIndividualControls" finished-at="2023-11-22T16:32:06 IST" duration-ms="19766" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[MultiChoice Not Displayed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: MultiChoice Not Displayed
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_001_SFI_All_Mobile.TestMobileIndividualControls(TC_001_SFI_All_Mobile.java:163)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestMobileIndividualControls -->
        <test-method is-config="true" signature="flush()[pri:0, instance:testCases.TC_001_SFI_All_Mobile@53d102a2]" started-at="2023-11-22T16:32:06 IST" name="flush" finished-at="2023-11-22T16:32:06 IST" duration-ms="626" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
      </class> <!-- testCases.TC_001_SFI_All_Mobile -->
    </test> <!-- chrometest -->
  </suite> <!-- Suite -->
</testng-results>
